"""add_rsa_key_columns_to_user

Revision ID: 2b350578cef1
Revises: b7f3e2c1d8a0
Create Date: 2026-09-06 22:47:35.701706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b350578cef1'
down_revision: Union[str, None] = 'b7f3e2c1d8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cases_case_number_key', 'cases', type_='unique')
    op.drop_index('ix_cases_case_number', table_name='cases')
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.add_column('users', sa.Column('rsa_private_key_enc', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('rsa_public_key', sa.Text(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'rsa_public_key')
    op.drop_column('users', 'rsa_private_key_enc')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.create_index('ix_cases_case_number', 'cases', ['case_number'], unique=False)
    op.create_unique_constraint('cases_case_number_key', 'cases', ['case_number'])
    # ### end Alembic commands ###
